#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
# Using build pattern: cmake
# autospec version: v24
# autospec commit: a88ffdc
#
# Source0 file verified with key 0xBB463350D6EF31EF (heiko@shruuf.de)
#
Name     : kfourinline
Version  : 25.04.0
Release  : 81
URL      : https://download.kde.org/stable/release-service/25.04.0/src/kfourinline-25.04.0.tar.xz
Source0  : https://download.kde.org/stable/release-service/25.04.0/src/kfourinline-25.04.0.tar.xz
Source1  : https://download.kde.org/stable/release-service/25.04.0/src/kfourinline-25.04.0.tar.xz.sig
Source2  : BB463350D6EF31EF.pkey
Summary  : No detailed summary available
Group    : Development/Tools
License  : BSD-3-Clause CC0-1.0 GFDL-1.2 GPL-2.0 LGPL-2.0 LGPL-2.1 LGPL-3.0
Requires: kfourinline-bin = %{version}-%{release}
Requires: kfourinline-data = %{version}-%{release}
Requires: kfourinline-license = %{version}-%{release}
Requires: kfourinline-locales = %{version}-%{release}
BuildRequires : buildreq-cmake
BuildRequires : buildreq-kde
BuildRequires : extra-cmake-modules-data
BuildRequires : gnupg
BuildRequires : kconfig-dev
BuildRequires : kcoreaddons-dev
BuildRequires : kcrash-dev
BuildRequires : kdbusaddons-dev
BuildRequires : kdnssd-dev
BuildRequires : ki18n-dev
BuildRequires : qt6base-dev
# Suppress stripping binaries
%define __strip /bin/true
%define debug_package %{nil}

%description
# KFourInLine
KFourInLine is a board game for two players based on the Connect-Four game. The
players try to build up a row of four pieces using different strategies.

%package bin
Summary: bin components for the kfourinline package.
Group: Binaries
Requires: kfourinline-data = %{version}-%{release}
Requires: kfourinline-license = %{version}-%{release}

%description bin
bin components for the kfourinline package.


%package data
Summary: data components for the kfourinline package.
Group: Data

%description data
data components for the kfourinline package.


%package doc
Summary: doc components for the kfourinline package.
Group: Documentation

%description doc
doc components for the kfourinline package.


%package license
Summary: license components for the kfourinline package.
Group: Default

%description license
license components for the kfourinline package.


%package locales
Summary: locales components for the kfourinline package.
Group: Default

%description locales
locales components for the kfourinline package.


%prep
mkdir .gnupg
chmod 700 .gnupg
gpg --homedir .gnupg --import %{SOURCE2}
gpg --homedir .gnupg --status-fd 1 --verify %{SOURCE1} %{SOURCE0} > gpg.status
grep -E '^\[GNUPG:\] (GOODSIG|EXPKEYSIG) BB463350D6EF31EF' gpg.status
%setup -q -n kfourinline-25.04.0
cd %{_builddir}/kfourinline-25.04.0
pushd ..
cp -a kfourinline-25.04.0 buildavx2
popd

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1744941601
mkdir -p clr-build
pushd clr-build
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
CLEAR_INTERMEDIATE_CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS"
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS"
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS"
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS"
ASFLAGS="$CLEAR_INTERMEDIATE_ASFLAGS"
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS"
export GOAMD64=v2
%cmake ..   -G 'Unix Makefiles'
make  %{?_smp_mflags}
popd
pushd ../buildavx2/
mkdir -p clr-build-avx2
pushd clr-build-avx2
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
CLEAR_INTERMEDIATE_CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS"
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS"
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS"
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS"
ASFLAGS="$CLEAR_INTERMEDIATE_ASFLAGS"
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS"
GOAMD64=v3
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -march=x86-64-v3 -Wl,-z,x86-64-v3 "
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -march=x86-64-v3 -Wl,-z,x86-64-v3 "
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -march=x86-64-v3 -Wl,-z,x86-64-v3 "
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS -march=x86-64-v3 "
%cmake ..   -G 'Unix Makefiles'
make  %{?_smp_mflags}
popd
popd

%install
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
CLEAR_INTERMEDIATE_CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS"
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS"
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS"
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS"
ASFLAGS="$CLEAR_INTERMEDIATE_ASFLAGS"
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS"
export SOURCE_DATE_EPOCH=1744941601
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/kfourinline
cp %{_builddir}/kfourinline-%{version}/CMakePresets.json.license %{buildroot}/usr/share/package-licenses/kfourinline/29fb05b49e12a380545499938c4879440bd8851e || :
cp %{_builddir}/kfourinline-%{version}/LICENSES/BSD-3-Clause.txt %{buildroot}/usr/share/package-licenses/kfourinline/9950d3fdce1cff1f71212fb5abd31453c6ee2f8c || :
cp %{_builddir}/kfourinline-%{version}/LICENSES/CC0-1.0.txt %{buildroot}/usr/share/package-licenses/kfourinline/8287b608d3fa40ef401339fd907ca1260c964123 || :
cp %{_builddir}/kfourinline-%{version}/LICENSES/GFDL-1.2-or-later.txt %{buildroot}/usr/share/package-licenses/kfourinline/7697008f58568e61e7598e796eafc2a997503fde || :
cp %{_builddir}/kfourinline-%{version}/LICENSES/GPL-2.0-or-later.txt %{buildroot}/usr/share/package-licenses/kfourinline/3e8971c6c5f16674958913a94a36b1ea7a00ac46 || :
cp %{_builddir}/kfourinline-%{version}/LICENSES/LGPL-2.0-only.txt %{buildroot}/usr/share/package-licenses/kfourinline/a4c60b3fefda228cd7439d3565df043192fef137 || :
cp %{_builddir}/kfourinline-%{version}/LICENSES/LGPL-2.0-or-later.txt %{buildroot}/usr/share/package-licenses/kfourinline/a4c60b3fefda228cd7439d3565df043192fef137 || :
cp %{_builddir}/kfourinline-%{version}/LICENSES/LGPL-2.1-only.txt %{buildroot}/usr/share/package-licenses/kfourinline/81b58c89ceef8e9f8bd5d00a287edbd15f9d3567 || :
cp %{_builddir}/kfourinline-%{version}/LICENSES/LGPL-3.0-only.txt %{buildroot}/usr/share/package-licenses/kfourinline/19d98e1b6f8ef12849ea4012a052d3907f336c91 || :
cp %{_builddir}/kfourinline-%{version}/LICENSES/LicenseRef-KDE-Accepted-LGPL.txt %{buildroot}/usr/share/package-licenses/kfourinline/e458941548e0864907e654fa2e192844ae90fc32 || :
cp %{_builddir}/kfourinline-%{version}/LICENSES/LicenseRef-KDE-Accepted-LGPL.txt %{buildroot}/usr/share/package-licenses/kfourinline/e458941548e0864907e654fa2e192844ae90fc32 || :
export GOAMD64=v2
pushd ../buildavx2/
GOAMD64=v3
pushd clr-build-avx2
%make_install_v3  || :
popd
popd
GOAMD64=v2
pushd clr-build
%make_install
popd
%find_lang kfourinline
/usr/bin/elf-move.py avx2 %{buildroot}-v3 %{buildroot} %{buildroot}/usr/share/clear/filemap/filemap-%{name}

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/V3/usr/bin/kfourinline
/V3/usr/bin/kfourinlineproc
/usr/bin/kfourinline
/usr/bin/kfourinlineproc

%files data
%defattr(-,root,root,-)
/usr/share/applications/org.kde.kfourinline.desktop
/usr/share/config.kcfg/kwin4.kcfg
/usr/share/icons/hicolor/128x128/apps/kfourinline.png
/usr/share/icons/hicolor/16x16/apps/kfourinline.png
/usr/share/icons/hicolor/22x22/apps/kfourinline.png
/usr/share/icons/hicolor/32x32/apps/kfourinline.png
/usr/share/icons/hicolor/48x48/apps/kfourinline.png
/usr/share/icons/hicolor/64x64/apps/kfourinline.png
/usr/share/kfourinline/themes/default.desktop
/usr/share/kfourinline/themes/default.rc
/usr/share/kfourinline/themes/default.svgz
/usr/share/kfourinline/themes/gray_reflection.desktop
/usr/share/kfourinline/themes/gray_reflection.rc
/usr/share/kfourinline/themes/gray_reflection.svgz
/usr/share/kfourinline/themes/yellow.desktop
/usr/share/kfourinline/themes/yellow.rc
/usr/share/kfourinline/themes/yellow.svgz
/usr/share/kfourinline/themes/yellow_reflection.desktop
/usr/share/kfourinline/themes/yellow_reflection.rc
/usr/share/metainfo/org.kde.kfourinline.appdata.xml
/usr/share/qlogging-categories6/kfourinline.categories
/usr/share/qlogging-categories6/kfourinline.renamecategories

%files doc
%defattr(0644,root,root,0755)
/usr/share/doc/HTML/ca/kfourinline/gameboard.png
/usr/share/doc/HTML/ca/kfourinline/index.cache.bz2
/usr/share/doc/HTML/ca/kfourinline/index.docbook
/usr/share/doc/HTML/ca/kfourinline/settings.png
/usr/share/doc/HTML/de/kfourinline/index.cache.bz2
/usr/share/doc/HTML/de/kfourinline/index.docbook
/usr/share/doc/HTML/en/kfourinline/gameboard.png
/usr/share/doc/HTML/en/kfourinline/index.cache.bz2
/usr/share/doc/HTML/en/kfourinline/index.docbook
/usr/share/doc/HTML/en/kfourinline/settings.png
/usr/share/doc/HTML/es/kfourinline/index.cache.bz2
/usr/share/doc/HTML/es/kfourinline/index.docbook
/usr/share/doc/HTML/et/kfourinline/index.cache.bz2
/usr/share/doc/HTML/et/kfourinline/index.docbook
/usr/share/doc/HTML/fr/kfourinline/index.cache.bz2
/usr/share/doc/HTML/fr/kfourinline/index.docbook
/usr/share/doc/HTML/it/kfourinline/index.cache.bz2
/usr/share/doc/HTML/it/kfourinline/index.docbook
/usr/share/doc/HTML/nl/kfourinline/index.cache.bz2
/usr/share/doc/HTML/nl/kfourinline/index.docbook
/usr/share/doc/HTML/pl/kfourinline/index.cache.bz2
/usr/share/doc/HTML/pl/kfourinline/index.docbook
/usr/share/doc/HTML/pt/kfourinline/index.cache.bz2
/usr/share/doc/HTML/pt/kfourinline/index.docbook
/usr/share/doc/HTML/pt_BR/kfourinline/index.cache.bz2
/usr/share/doc/HTML/pt_BR/kfourinline/index.docbook
/usr/share/doc/HTML/sl/kfourinline/index.cache.bz2
/usr/share/doc/HTML/sl/kfourinline/index.docbook
/usr/share/doc/HTML/sv/kfourinline/index.cache.bz2
/usr/share/doc/HTML/sv/kfourinline/index.docbook
/usr/share/doc/HTML/uk/kfourinline/gameboard.png
/usr/share/doc/HTML/uk/kfourinline/index.cache.bz2
/usr/share/doc/HTML/uk/kfourinline/index.docbook
/usr/share/doc/HTML/uk/kfourinline/settings.png

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/kfourinline/19d98e1b6f8ef12849ea4012a052d3907f336c91
/usr/share/package-licenses/kfourinline/29fb05b49e12a380545499938c4879440bd8851e
/usr/share/package-licenses/kfourinline/3e8971c6c5f16674958913a94a36b1ea7a00ac46
/usr/share/package-licenses/kfourinline/7697008f58568e61e7598e796eafc2a997503fde
/usr/share/package-licenses/kfourinline/81b58c89ceef8e9f8bd5d00a287edbd15f9d3567
/usr/share/package-licenses/kfourinline/8287b608d3fa40ef401339fd907ca1260c964123
/usr/share/package-licenses/kfourinline/9950d3fdce1cff1f71212fb5abd31453c6ee2f8c
/usr/share/package-licenses/kfourinline/a4c60b3fefda228cd7439d3565df043192fef137
/usr/share/package-licenses/kfourinline/e458941548e0864907e654fa2e192844ae90fc32

%files locales -f kfourinline.lang
%defattr(-,root,root,-)

